const btns = document.querySelectorAll("button");
const display = document.getElementById("display");
const equal = document.getElementById("equal");
const result = document.getElementById("result");
const clearBtn = document.querySelector("[value=C]");
const eraseBtn = document.querySelector("[value=backSpace]");
const dotBtn = document.getElementById("dot");

function displayValue() {
    const regexForNum = /\d/;
    const regexForOperator = /[x÷+-]/;
    const regexForDot = /\./;

    const checkOperator = display.textContent[display.textContent.length - 2];

    result.textContent = "";

    if (regexForNum.test(this.value)) {     // test the value passed and resets de textContent so it won't display things like 013 or 000

        if (display.textContent === "0") {
            display.textContent = "";
        }

        display.textContent += this.value;

    } else if (regexForOperator.test(this.value) && display.textContent !== "0") {  // doesn't let things like 0 + 2 be displayed


        if (!checkOperator || !regexForOperator.test(checkOperator)) {  // ensures only one operator is shown, avoiding things like 2++5
            display.textContent += ` ${this.value} `;
        }

    } else if (regexForDot.test(this.value) && (!checkOperator || !regexForOperator.test(checkOperator))) {
        const text = display.textContent;
        const textSplit = text.split(" ");
        if (!textSplit[textSplit.length - 1].includes(".")) {
            display.textContent += this.value;
        }
    }

}

function fixOperators() {       // takes the value generated by displayValue and trasnforms into an array of numbers and operators
    const valueDisplayed = display.textContent;

    return valueDisplayed.replace(/x|÷/g, match => {
        return match === 'x' ? '*' : '/';
    }).split(" ").map(elem => {
        const regex = /[*/+-]/;
        return regex.test(elem) ? elem : +elem;
    });
}

function fixPriority(array) {
    const copyArray = [...array];

    if (!array.includes("*") && !array.includes("/")) return copyArray;

    const indexOfMult = array.indexOf("*");
    const indexOfDiv = array.indexOf("/");

    if ((indexOfMult < indexOfDiv || indexOfDiv === -1) && indexOfMult >= 0) {  // takes * and the elements immediately before and after and puts into copyArray as a nested array in the place of the original 3 elements
        const splitSlice = array.slice(indexOfMult - 1, indexOfMult + 2);

        copyArray.splice(indexOfMult - 1, 3, splitSlice);

        return fixPriority(copyArray)
    } else if ((indexOfMult > indexOfDiv || indexOfMult === -1) && indexOfDiv >= 0) {
        const splitSlice = array.slice(indexOfDiv - 1, indexOfDiv + 2);

        copyArray.splice(indexOfDiv - 1, 3, splitSlice);

        return fixPriority(copyArray)
    }
}

function operate() {

    const fixed = fixPriority(fixOperators());

    const newArr = fixed.map(value => {  // ensures that multiplication and division are made first
        function test(value) {
            if (Array.isArray(value)) {
                if (value[1] === "*") {
                    return test(value[0]) * value[2]
                } else {
                    return test(value[0]) / value[2]
                }
            } else {
                return value;
            }
        }
        return test(value)
    })

    return newArr.reduce((total, currVal, index, thisArr) => {
        if (currVal === "+") {
            return total + thisArr[index + 1];
        } else if (currVal === "-") {
            return total - thisArr[index + 1];
        } else {
            return total;
        }
    }, newArr[0]);
}

function displayResult() {
    const text = display.textContent;

    if (text.includes("÷")) {
        const textSplit = text.split(" ");

        for (let i = 0; i < textSplit.length; i++) {
            if ((textSplit[i] === "÷" && textSplit[i + 1] === "0") || (textSplit[i] === "÷" && textSplit[i + 1] === "")) {
                result.textContent = "I see what you did there, it won't crash baby ;)"
                return;
            }
        }
    }

    const total = operate();

    result.textContent = Number.isInteger(total) ? total : total.toFixed(2);
}

function clear() {
    display.textContent = "0";
    result.textContent = "";
}

function erase() {
    const text = display.textContent;
    result.textContent = "";

    if (text[text.length - 1] === " ") {

        display.textContent = text.slice(0, text.length - 3);
    } else if (text.length === 1) {

        display.textContent = "0";
    } else {

        display.textContent = text.slice(0, text.length - 1);
    }
}

function keyboard(e) {
    const regexForNum = /^\d+$/;
    const regexForOperator = /[\*/+-]/;
    const regexForDot = /\./;

    const checkOperator = display.textContent[display.textContent.length - 2];

    result.textContent = "";
    if (regexForNum.test(e.key)) {

        if (display.textContent === "0") {
            display.textContent = "";
        }

        display.textContent += e.key;

    } else if (regexForOperator.test(e.key) && display.textContent !== "0") {

        if (!checkOperator || !regexForOperator.test(checkOperator)) {
            if (e.key === "*") {
                display.textContent += ` x `;
            } else if (e.key === "/") {
                display.textContent += ` ÷ `;
            } else {
                display.textContent += ` ${e.key} `;
            }
        }

    } else if (regexForDot.test(e.key) && (!checkOperator || !regexForOperator.test(checkOperator))) {
        const text = display.textContent;
        const textSplit = text.split(" ");
        if (!textSplit[textSplit.length - 1].includes(".")) {
            display.textContent += e.key;
        }
    }
}

btns.forEach(btn => btn.addEventListener("click", displayValue));
equal.addEventListener("click", displayResult);
clearBtn.addEventListener("click", clear);
eraseBtn.addEventListener("click", erase);
window.addEventListener("keydown", keyboard);
window.addEventListener("keydown", function(e) {
    if(e.key === "Backspace") {
        erase();
    }
});
window.addEventListener("keydown", function(e) {
    if(e.key === "Enter") {
        displayResult();
    }
});